language: java
jdk:
 - oraclejdk8
addons:
  sonarcloud:
    organization: "ralfschiffert-github" # the key of the org you chose at step #3
    token:
      secure: f89cec04cec46fa2c9873216eb331d0b15e4c81c  # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
